document.writeln("<!--script type=\"text/javascript\">");
document.writeln("	atOptions = {");
document.writeln("		\'key\' : \'28a5ce34bdb529d290595736475e2679\',");
document.writeln("		\'format\' : \'iframe\',");
document.writeln("		\'height\' : 600,");
document.writeln("		\'width\' : 160,");
document.writeln("		\'params\' : {}");
document.writeln("	};");
document.writeln("	document.write(\'<scr\' + \'ipt type=\"text/javascript\" src=\"http\' + (location.protocol === \'https:\' ? \'s\' : \'\') + \'://www.topcreativeformat.com/28a5ce34bdb529d290595736475e2679/invoke.js\"></scr\' + \'ipt>\');");
document.writeln("</script-->");
