document.writeln("<!--script type=\"text/javascript\">");
document.writeln("	atOptions = {");
document.writeln("		\'key\' : \'ea1f17d0b969f24752ab804615e84b6b\',");
document.writeln("		\'format\' : \'iframe\',");
document.writeln("		\'height\' : 90,");
document.writeln("		\'width\' : 728,");
document.writeln("		\'params\' : {}");
document.writeln("	};");
document.writeln("	document.write(\'<scr\' + \'ipt type=\"text/javascript\" src=\"http\' + (location.protocol === \'https:\' ? \'s\' : \'\') + \'://www.topcreativeformat.com/ea1f17d0b969f24752ab804615e84b6b/invoke.js\"></scr\' + \'ipt>\');");
document.writeln("</script-->");
