document.writeln("<!--script type=\"text/javascript\">");
document.writeln("	atOptions = {");
document.writeln("		\'key\' : \'8da6deb0bfbda4ed848b5f82176a8e9b\',");
document.writeln("		\'format\' : \'iframe\',");
document.writeln("		\'height\' : 90,");
document.writeln("		\'width\' : 728,");
document.writeln("		\'params\' : {}");
document.writeln("	};");
document.writeln("	document.write(\'<scr\' + \'ipt type=\"text/javascript\" src=\"http\' + (location.protocol === \'https:\' ? \'s\' : \'\') + \'://www.profitabledisplaynetwork.com/8da6deb0bfbda4ed848b5f82176a8e9b/invoke.js\"></scr\' + \'ipt>\');");
document.writeln("</script-->");
